config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'stashs#index'

  resources :milks, only: [:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/milk.rb
class Milk < ApplicationRecord
  validates :milk_type,
    presence: true,
    inclusion: { in: %w(fresh frozen thawed),
      message: "%{value} is not a valid milk type" }
  validates :date, presence: true
  validates :amount, presence: true,
    numericality: { only_integer: true }

  def get_exp_date(milk_type, date)
    #https://www.cdc.gov/breastfeeding/recommendations/handling_breastmilk.htm
    # assuming for now that fresh means in the refridgerator: 5 days
    # frozen means freezer compartment with separate doors: 3-6 months
    # thawed milk needs to be used in 24 hours - expiration date is today;
    case milk_type
      when 'fresh'
        return date.advance(days: 5)
      when 'frozen'
        return date.advance(months: 6)
      when 'thawed'
        return date
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/milks_controller.rb
class MilksController < ApplicationController
  def create
    @milk = Milk.new(milk_params)
    # matches /stash formatting of downcase
    @milk.milk_type.downcase!
    @milk.location = "home"
    @milk.exp_date = @milk.get_exp_date(@milk.milk_type, @milk.date)

    @milk.save!

    @milks = Milk.where.not(milk_type: "consumed").order(exp_date: "asc")

    # will need to tackle error handling later
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js # render milks/create.js.erb
    end
  end

  def update
    @milk = Milk.find(params[:id])
    @milk.update(milk_params)
    # matches /stash formatting of downcase
    @milk.milk_type.downcase!
    # recompute the expiration date based on the date of change
    @milk.exp_date = @milk.get_exp_date(@milk.milk_type, Time.now)

    @milk.save!

    @milks = Milk.where.not(milk_type: "consumed").order(exp_date: "asc")

    # will need to tackle error handling later
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js # render milks/update.js.erb
    end
  end

def destroy
  @milk = Milk.find(params[:id])
  @milk.destroy

  @milks = Milk.where.not(milk_type: "consumed").order(exp_date: "asc")


  respond_to do |format|
    format.html { redirect_to root_path }
    format.js # render milks/destroy.js.erb
  end
end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def milk_params
    params.require(:milk).permit(:milk_type, :date, :amount)
  end
end

app/controllers/stashs_controller.rb
class StashsController < ApplicationController
  def index
    @milk  = Milk.new
    @milks = Milk.where.not(milk_type: "consumed").order(exp_date: "asc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milks_helper.rb
module MilksHelper
end

app/helpers/stashs_helper.rb
module StashsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag "favicon.ico" %>
  <title>/stash</title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <div class="container-fluid">
    <header>
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-pills top-nav">
            <li class="logo">
              <%= image_tag "smaller-baby-bottle.png", class: "pull-left img-responsive" %>
              <%= link_to "/stash", "http://www.slash-stash.com", class: "logo-text" %>
            </li>
            <li class="pull-right">
              <%= link_to "My Stash", "#", id: "milks-link" %>
            </li>
          </ul>
        </header>
        <main>
          <%= yield %>
        </main>
        <footer>
          <div class="row">
            <div class="col-md-3">
              <ul class="nav nav-stacked nav-pills">
                <li class="first-footer-link">
                  <p>Making /stash</p>
                </li>
                <li>
                  <a href="https://github.com/nahmisa/capstone-stash">GitHub</a>
                </li>
                <li>
                  <a href="https://claudiajs.com/">Claudia.js</a>
                </li>
                <li>
                  <a href="https://www.luis.ai/">LUIS.ai</a>
                </li>
                <li>
                  <a href="https://slack.com/apps/category/At0EFRCDNY-developer-tools">Slack</a>
                </li>
              </ul>
            </div>
            <div class="col-md-3">
              <ul class="nav nav-stacked nav-pills">
                <li class="second-footer-link">
                  <p>Sarah</p>
                  <li>
                    <a href="https://github.com/nahmisa">GitHub</a>
                  </li>
                  <li>
                    <a href="https://www.linkedin.com/in/sarahnahmias">LinkedIn</a>
                  </li>
                </ul>
              </div>
              <div class="col-md-3">
                <ul class="nav nav-stacked nav-pills">
                  <li class="third-footer-link">
                    <p class="title-top">Ada Developers Academy</p>
                  </li>
                  <li>
                    <a href="http://adadevelopersacademy.org/">About</a>
                  </li>
                  <li>
                    <a href="http://adadevacademy.tumblr.com/">Blog</a>
                  </li>
                  <li>
                    <a href="https://twitter.com/adaacademy?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor">Twitter</a>
                  </li>
                </ul>
              </div>
              <div class="col-md-3">
                <ul class="nav nav-stacked nav-pills">
                  <li class="last-footer-link">
                    <p class="title-top">Handy Links</p>
                  </li>
                  <li>
                    <a href="https://www2.aap.org/breastfeeding/faqsBreastfeeding.html">American Academy of Pediatrics</a>
                  </li>
                  <li>
                    <a href="http://www.donatemilk.org/">NW Milkbank</a>
                  </li>
                  <li>
                    <a href="http://www.swedish.org/locations/center-for-perinatal-bonding-and-support">Perinatal Bonding & Support</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="row">
              <div class="bottom-border col-lg-12">
              </div>
            </div>
          </footer>
        </div>
      </body>
      </html>

app/views/milks/_milk.html.erb
<tr>
  <%= form_for milk, remote: true do |f|  %>
  <td>
    <%= f.text_field :milk_type %>
  </td>
  <td>
    <%= milk.exp_date.strftime("%A, %B %e, %Y")   #=> "Thursday, June 9, 2011"
    %>
  </td>
  <td>
    <%= f.text_field :amount %>
  </td>
  <td>
    <%= f.submit 'Update', class: 'btn btn-success form-control add-btn' %>
  </td>
    <% end %>
  <td>
    <%= link_to 'Delete', milk_path(milk),
      class: "btn btn-danger",
      method: :delete,
      remote: true,
      data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/milks/create.js.erb
$('#milk').append("<%= j render @milk %>");
// clear the form after we add a new row
$('#milk_milk_type').val("").focus();
$('#milk_location').val("");
$('#milk_date').val("");
$('#milk_amount').val("");

app/views/milks/destroy.js.erb
$('#milk').html("<%= j render @milks %>");
$('#milk_milk_type').val("").focus();

app/views/milks/update.js.erb
$('#milk').html("<%= j render @milks %>");
$('#milk_milk_type').val("").focus();

app/views/stashs/index.html.erb
<div class="jumbotron">
  <%= image_tag "smaller-baby-face.png", class: "baby-face pull-right img-responsive" %>
  <section id="stash-info">
    <h1>
      For busy breastfeeding moms...
    </h1>
    <p>
      ...who need to ensure reliable milk production and don't have mind space to keep track of production, consumption, inventory and expiration dates constantly.  We take the tediousness out of recording your supply with a bot that runs on apps you're already using.
    </p>
    <div class="middle-me">
      <%= link_to "Learn More", "#", class: "btn-lg btn-success", id: "learn-more" %>
    </div>
    <div id="stash-more-info">
      <div class="boxed middle-me">
        <h1 class="anchor" title="How to"><span class="how-to-stash">How-to /stash</span></h1>
        <ul class="how-to">
          <li>
            <strong><a href="https://slack.com/downloads">Start using Slack</a></strong>
            <span class="secondary-text"> to organize your team at work or at home</span>
          </li>
          <li>
            <strong><a href="https://slack.com/apps">Download our app</a></strong>
            <span class="secondary-text"> to start tracking.</span>
          </li>
          <li>
            <strong><a href="#" id="milks-link2">Record your current milk inventory</a> </strong>
            <span class="secondary-text">to get started.</span>
          </li>
          <li>
            <strong><a href="https://api.slack.com/slash-commands">Use /stash in Slack</a></strong>
            <span class="secondary-text"> to easily update your stash.</span>
          </li>
          <li>
            <strong>Talk to the bot like you would a human </strong>
            <span class="secondary-text"> - no complicated commands to memorize!</span>
          </li>
          <li>
            <strong>Get your baby's other caretakers involved. </strong>
            <span class="secondary-text"> From dads to daycares, your support network can also be involved in tracking your stash.</span>
          </li>
        </ul>
        <div class="middle-me">
          <%= link_to "Ok, got it!", "#", class: "btn-lg btn-success", id: "close-learn" %>
        </div>
      </div>
    </div>
  </section>
  <section id="milk-info">
    <h1>
      My stash
    </h1>
    <p>
      Onboard your inventory here, and then update easily through the /slack command.  Check back any time to view and edit your stash by clicking on the fields in the table below.  Expiration dates are re-computed whenever the type of milk changes.
    </p>
  </section>
  <section id="milks-section">
    <%= form_for @milk, html: { class: "form-inline" }, remote: true do |f| %>
    <fieldset>
      <div class="form-group col-xs-3">
        <label for="milk_milk_type" class="control-label">
          Type
        </label>
        <%= f.text_field :milk_type, class: "form-control", placeholder: "fresh, frozen or thawed" %>
      </div>
      <div class="form-group col-xs-3">
        <label for="milk_date" class="control-label">
          Date
        </label>
        <%= f.date_field :date, class: "form-control" %>
        <small class="help-block">
          When pumped/frozen/thawed
        </small>
      </div>
      <div class="form-group col-xs-3">
        <label for="milk_amount" class="control-label">
          Amount
        </label>
        <%= f.number_field :amount, class: "form-control", placeholder: "number of ounces" %>
      </div>
      <div class="form-group col-xs-3">
        <%= f.submit 'Add', class: 'btn btn-success form-control add-btn' %>
      </div>
    </fieldset>
    <% end %>
    <div class="milk-table-container">
      <table class="table table-hover table-condensed">
        <thead>
          <tr>
            <th>
              Type
            </th>
            <th>
              Expiration Date
            </th>
            <th>
              Amount (oz)
            </th>
          </tr>
        </thead>
        <tbody id="milk">
          <%= render @milks %>
        </tbody>
      </table>
    </div>
  </section>
</div>
</div>
</div>